import "./globals.css";
import { JetBrains_Mono, Inter } from "next/font/google";
import { ReactNode } from "react";

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-heading",
  display: "swap",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={`${jetbrains.variable} ${inter.variable}`}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
